---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
- test/
engines:
  eslint:
    enabled: true
  csslint:
    enabled: true
ratings:
  paths:
    - server/**
    - sass/**
    - test/**
    - public/app/**
    - public/index-build.html
