language: node_js
node_js:
  "6.1"
before_script:
  - npm install -g gulp
script:
  - gulp lint
  - gulp test
  - gulp &

deploy:
  on:
    branch: master
  provider: heroku
  api_key:
    secure: "YOUR ENCRYPTED API KEY"

after_success:
  - bash <(curl -s https://codecov.io/bash)
